"""Tests for RFC 8785 canonical JSON implementation."""

import hashlib
import pytest

from aegis_sdk.canon import canonicalize, hash_object, hash_object_hex


def test_key_ordering():
    obj = {"z": 1, "a": 2, "m": 3}
    assert canonicalize(obj) == b'{"a":2,"m":3,"z":1}'


def test_nested_object():
    obj = {"b": {"y": True, "x": False}, "a": [3, 1, 2]}
    assert canonicalize(obj) == b'{"a":[3,1,2],"b":{"x":false,"y":true}}'


def test_null_and_bool():
    assert canonicalize(None) == b"null"
    assert canonicalize(True) == b"true"
    assert canonicalize(False) == b"false"


def test_string_escaping():
    assert canonicalize("hello") == b'"hello"'
    assert canonicalize('say "hi"') == b'"say \\"hi\\""'


def test_array():
    assert canonicalize([1, 2, 3]) == b"[1,2,3]"
    assert canonicalize([]) == b"[]"


def test_hash_deterministic():
    obj = {"tenant_id": "t1", "session_id": "s1", "seq": 1, "event_type": "TOOL_CALL_PROPOSED"}
    h1 = hash_object(obj)
    h2 = hash_object(obj)
    assert h1 == h2
    assert len(h1) == 32


def test_hash_hex():
    obj = {"a": 1}
    h = hash_object_hex(obj)
    assert len(h) == 64
    assert all(c in "0123456789abcdef" for c in h)


# Cross-platform golden test.
# The expected hash was generated by running the Go TestGoldenHash test
# after the first full run (update this value from Go output).
# This test enforces byte-for-byte parity between Go and Python.
GOLDEN_INPUT = {
    "event_type": "TOOL_CALL_PROPOSED",
    "seq": 1,
    "session_id": "session-abc",
    "tenant_id": "tenant-xyz",
    "ts_unix_ms": 1700000000000,
}


def test_golden_hash_cross_platform():
    """Python must produce the same hash as Go for identical input."""
    canonical = canonicalize(GOLDEN_INPUT)
    got = hashlib.sha256(canonical).hexdigest()
    # Canonical form must be deterministic.
    assert canonical == b'{"event_type":"TOOL_CALL_PROPOSED","seq":1,"session_id":"session-abc","tenant_id":"tenant-xyz","ts_unix_ms":1700000000000}'
    # Hash length must be 64 hex chars.
    assert len(got) == 64
    # Store the actual value for cross-platform pinning.
    # Once the Go side produces its value, pin it here and in the Go test.
    print(f"\ngolden hash: {got}")
